#:schema node_modules/wrangler/config-schema.json

name = "yukio-api"
main = "src/index.ts"
compatibility_date = "2026-10-08"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "yukio-ratings-db"
database_id = "ce7d02c0-431c-40b7-8771-3397fd6278ea"

[ai]
binding = "AI"

[observability]
enabled = true

[vars]
YUKIO_DATA_REPO = "bimaakbar-dev/yukio-data"
YUKIO_DATA_BRANCH = "main"
ANILIST_SORT = "popular"
MAX_EPISODES = "100"
MAX_CHARACTERS = "100"
START_PAGE = "1"
PAGE_STEP = "2"
PATCH_SHARD = "1"
PATCH_TOTAL_SHARDS = "2"

[dev]
port = 8787
local_protocol = "http"
